package fui

import "image/color"

func rgba(c uint32) color.RGBA {
	return color.RGBA{A: uint8(c >> 24), R: uint8(c >> 16), G: uint8(c >> 8), B: uint8(c)}
}

var P9Palette = map[string]color.RGBA{
	"black":                 rgba(0xff000000),
	"light-black":           rgba(0xff222222),
	"blue":                  rgba(0xff3030cf),
	"blue-lite-blue":        rgba(0xff3080cf),
	"blue-orange":           rgba(0xff80a830),
	"blue-red":              rgba(0xff803080),
	"dark":                  rgba(0xff303030),
	"dark-blue":             rgba(0xff303080),
	"dark-blue-lite-blue":   rgba(0xff305880),
	"dark-blue-orange":      rgba(0xff584458),
	"dark-blue-red":         rgba(0xff583058),
	"dark-gray":             rgba(0xff656565),
	"dark-grayi":            rgba(0xff535353),
	"dark-grayii":           rgba(0xff424242),
	"dark-green":            rgba(0xff308030),
	"dark-green-blue":       rgba(0xff305858),
	"dark-green-lite-blue":  rgba(0xff308058),
	"dark-green-orange":     rgba(0xff586c30),
	"dark-green-red":        rgba(0xff585830),
	"dark-green-yellow":     rgba(0xff588030),
	"dark-lite-blue":        rgba(0xff308080),
	"dark-orange":           rgba(0xff805830),
	"dark-purple":           rgba(0xff803080),
	"dark-red":              rgba(0xff803030),
	"dark-yellow":           rgba(0xff808030),
	"gray":                  rgba(0xff808080),
	"green":                 rgba(0xff30cf30),
	"green-blue":            rgba(0xff308080),
	"green-lite-blue":       rgba(0xff30cf80),
	"green-orange":          rgba(0xff80a830),
	"green-red":             rgba(0xff808030),
	"green-yellow":          rgba(0xff80cf30),
	"light":                 rgba(0xffcfcfcf),
	"light-blue":            rgba(0xff8080cf),
	"light-blue-lite-blue":  rgba(0xff80a8cf),
	"light-blue-orange":     rgba(0xffa894a8),
	"light-blue-red":        rgba(0xffa880a8),
	"light-gray":            rgba(0xff888888),
	"light-grayi":           rgba(0xff9a9a9a),
	"light-grayii":          rgba(0xffacacac),
	"light-grayiii":         rgba(0xffbdbdbd),
	"light-green":           rgba(0xff80cf80),
	"light-green-blue":      rgba(0xff80a8a8),
	"light-green-lite-blue": rgba(0xff80cfa8),
	"light-green-orange":    rgba(0xffa8bc80),
	"light-green-red":       rgba(0xffa8a880),
	"light-green-yellow":    rgba(0xffa8cf80),
	"light-lite-blue":       rgba(0xff80cfcf),
	"light-orange":          rgba(0xffcfa880),
	"light-purple":          rgba(0xffcf80cf),
	"light-red":             rgba(0xffcf8080),
	"light-yellow":          rgba(0xffcfcf80),
	"lite-blue":             rgba(0xff30cfcf),
	"orange":                rgba(0xffcf8030),
	"purple":                rgba(0xffcf30cf),
	"red":                   rgba(0xffcf3030),
	"white":                 rgba(0xffffffff),
	"dark-white":            rgba(0xffdddddd),
	"yellow":                rgba(0xffcfcf30),
}

var LightTheme = map[string]color.RGBA{
	"Black":         P9Palette["black"],
	"Dark":          P9Palette["dark"],
	"DarkGray":      P9Palette["dark-grayii"],
	"DarkGrayI":     P9Palette["dark-grayi"],
	"DarkGrayII":    P9Palette["dark-gray"],
	"DarkGrayIII":   P9Palette["dark"],
	"Gray":          P9Palette["gray"],
	"Light":         P9Palette["light"],
	"LightGray":     P9Palette["light-grayiii"],
	"LightGrayI":    P9Palette["light-grayii"],
	"LightGrayII":   P9Palette["light-grayi"],
	"LightGrayIII":  P9Palette["light-gray"],
	"White":         P9Palette["white"],

	"ButtonBg":      P9Palette["blue-lite-blue"],
	"ButtonBgDim":   rgba(0xff30809a),
	"ButtonText":    P9Palette["light"],
	"ButtonTextDim": P9Palette["light-grayii"],
	"Check":         P9Palette["orange"],
	"Danger":        P9Palette["red"],
	"DocBg":         P9Palette["black"],
	"DocBgDim":      P9Palette["light-grayii"],
	"DocBgHilite":   P9Palette["light-black"],
	"DocText":       P9Palette["light"],
	"DocTextDim":    P9Palette["light-gray"],
	"Fatal":         rgba(0xff880000),
	"Hint":          P9Palette["light-gray"],
	"Info":          P9Palette["blue-lite-blue"],
	"InvText":       P9Palette["light"],
	"PanelBg":       P9Palette["dark"],
	"PanelBgDim":    P9Palette["light-gray"],
	"PanelText":     P9Palette["light"],
	"PanelTextDim":  P9Palette["light-grayii"],
	"Primary":       P9Palette["green-blue"],
	"Secondary":     P9Palette["dark-purple"],
	"Success":       P9Palette["green"],
	"Transparent":   P9Palette["00000000"],
	"Warning":       P9Palette["yellow"],
}

var DarkTheme = map[string]color.RGBA{
	"Black":         P9Palette["black"],
	"Dark":          P9Palette["dark"],
	"DarkGray":      P9Palette["dark-grayii"],
	"DarkGrayI":     P9Palette["dark-grayi"],
	"DarkGrayII":    P9Palette["dark-gray"],
	"DarkGrayIII":   P9Palette["dark"],
	"Gray":          P9Palette["gray"],
	"Light":         P9Palette["light"],
	"LightGray":     P9Palette["light-grayiii"],
	"LightGrayI":    P9Palette["light-grayii"],
	"LightGrayII":   P9Palette["light-grayi"],
	"LightGrayIII":  P9Palette["light-gray"],
	"White":         P9Palette["white"],

	"ButtonBg":      P9Palette["blue-lite-blue"],
	"ButtonBgDim":   rgba(0xff30809a),
	"ButtonText":    P9Palette["light"],
	"ButtonTextDim": P9Palette["light-grayii"],
	"Check":         P9Palette["orange"],
	"Danger":        P9Palette["red"],
	"DocBg":         P9Palette["light"],
	"DocBgDim":      P9Palette["dark-grayi"],
	"DocBgHilite":   P9Palette["dark-white"],
	"DocText":       P9Palette["dark"],
	"DocTextDim":    P9Palette["light-grayi"],
	"Fatal":         rgba(0xff880000),
	"Hint":          P9Palette["light-gray"],
	"Info":          P9Palette["blue-lite-blue"],
	"InvText":       P9Palette["light"],
	"PanelBg":       P9Palette["white"],
	"PanelBgDim":    P9Palette["dark-grayi"],
	"PanelText":     P9Palette["dark"],
	"PanelTextDim":  P9Palette["dark-grayii"],
	"Primary":       P9Palette["green-blue"],
	"Secondary":     P9Palette["dark-purple"],
	"Success":       P9Palette["dark-green"],
	"Transparent":   P9Palette["00000000"],
	"Warning":       P9Palette["light-orange"],
}
